version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: development
    volumes:
      - ./volume/mysql:/var/lib/mysql
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bundle exec bin/rails server
    volumes:
      - ./:/app
      - ./volume/bundle_install:/app/vendor/bundle
      - ./volume/bundle:/app/.bundle
      - ./volume/node_modules:/app/node_modules
    ports:
      - 3000:3000
    links:
      - mysql
    environment:
      DATABASE_URL: mysql2://root:root@mysql:3306
      MYSQL_ROOT_PASSWORD: root
      DATABASE_NAME: development
      RAILS_ENV: development